spring:
  datasource:
    url: "jdbc:h2:file:/path/to/database/file;DB_CLOSE_DELAY=-1"
    username: sa
    password: password
    driverClassName: org.h2.Driver
    initialization-mode: always
    schema: classpath:schema.sql
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: INFO
    com.michaelpippolito.fantasy: DEBUG

mlb-year: 2023

throttle:
  amountMs: 2000